server:
  port: 9194
spring:
  profiles:
    active: dev
  application:
    name: user-service
  config:
      import: optional:configserver:http://10.82.14.80:8888

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info
welcome:
  message: Development